### ISSUE TITLE
Add Email Validation

### ISSUE THREAD

**Issue by saefullohmaslul** [faceair/jio#1]
## Expected:

- Validation for email

## Method:

- jio.Email()

**Comment by faceair** [comment]
Designing a very strict rule to verify email is difficult, see
1. https://emailregex.com
2. https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/

Also because golang's regular expression engine is not compatible with PCRE, the regular expressions in the link above cannot be used directly.

For a very simple check, you could try:
```
jio.String().Regex(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$`)
```
